### ISSUE TITLE
Remove componentWillReceiveProps warning

### ISSUE THREAD

**Issue by VBT-BB** [bberak/nature-of-code-app#39] opened 2019-11-22 14:55 UTC
Could we change `componentWillReceiveProps` [here](https://github.com/bberak/react-native-game-engine/blob/master/src/GameEngine.js#L62) into `UNSAFE_componentWillReceiveProps` to stop having a yellow warning at start ?

**Comment by bberak** [comment] 2019-11-23 02:39
Hi @VBT-BB,

Yeah I hear you.. This is definitely a priority. The problem is that renaming `componentWillReceiveProps` to `UNSAFE_componentWillReceiveProps` will not be backwards compatible with older versions of React. This is unfortunate - but I think inevitable. I'll need to update the `peerDependencies` and `version` to reflect the breaking change. Are you able to hide the warning box until we sort this out?

**Comment by VBT-BB** [comment] 2019-11-25 16:49
I agree with you, for the moment I have a postinstall script to replace `componentWillReceiveProps` in `UNSAFE_componentWillReceiveProps` in files that I wish to modify, thanks for the quick answer

**Comment by bberak** [comment] 2019-11-27 09:04
No worries @VBT-BB - that's a nice interim fix. Cheers.

**Comment by rafaelmaeuer** [comment] 2019-12-07 11:44
Nice to find out this problem is already on track :D

**Comment by bberak** [comment] 2020-01-04 07:25
Hi @VBT-BB and @rafaelmaeuer,

These warnings should be fixed in version `1.0.0`. A peer dependency of React >= 16.3.0 is required.

Cheers!

**Closed as completed by bberak** 2020-01-04 07:25 UTC
