### ISSUE TITLE
Touch event not firing on the canvas

### ISSUE THREAD

**Issue by ohmlnz** [bberak/nature-of-code-app#15] opened 2019-02-11 06:11 UTC
Hi there,

I've been playing around with your engine for a bit and don't quite understand why my clicks are not being registered. They fire properly when hitting sprites but don't when clicking on the canvas. I've tried to reproduce one of the example in your handbook repo (rigid bodies), which works fine on its end, but not on mine... Am I missing something?

```jsx
import { fireEvent } from './systems';

...

const engine = Matter.Engine.create({ enableSleeping: false });
const world = engine.world;

return (
      <GameEngine
        systems={[fireEvent]}
        entities={{
          physics: { engine: engine, world: world }
        }}
      >
      </GameEngine>
)
```
and then:

```js
const fireEvent = (state, { touches }) => {
	touches.filter(t => t.type === "press").forEach(t => {
		console.log(t)
	});

	return state;
};

export { fireEvent };

```

Thanks for your help!

**Comment by bberak** [comment] 2019-02-11 08:10
Hi @OthmanLan,

Have you applied any specific styling onto the GameEngine and or its parent?

Is the parent a standard View? If so, have you assigned any props to the parent View?

Your code looks fine from first glance - I'll try reproduce the bug once I get the above details from you.

The following would also help:

- How did you create the app - ```react-native init``` or via Expo?
- RN version, Expo version (if using Expo)
- iOS or Android

Cheers!

**Comment by ohmlnz** [comment] 2019-02-12 01:45
Hi @bberak,

Thanks for your help!

I haven't applied any specific styling except for a flex property on the parent container and a background color on the GameEngine component. The parent is a standard View and I'm not passing down any props. 

As for your questions:

- I used `expo init` to create my project and applied the default settings
- The project runs with Expo 32.0.0 and this version of RN: https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz
- iOS only at the moment

I hope that helps. I'll continue to investigate on my end :)

**Comment by bberak** [comment] 2019-02-12 13:42
Thanks for the info @OthmanLan.

I believe the issue is caused by having the ```alignItems: "center"``` style on the parent component. I don't quite understand why, however I think this must be caused by a recent change to the react-native SDK that gets bundled with Expo (https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz).

There might even be a good reason for this failure, but I cannot speculate on this given that I haven't found the root cause. That said, if you remove the property, it should work. Here's a snippet I have tested on my device - let me know if it works for you too:

```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { GameEngine } from "react-native-game-engine";

const fireEvent = (entities, { touches }) => {
  console.log("Presses:", touches.filter(x => x.type == "press").length)
  return entities;
}

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <GameEngine style={{ backgroundColor: "red" }} systems={[fireEvent]} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    //-- alignItems style seems to cause the issue..
    //alignItems: 'center',
    justifyContent: 'center',
  },
});
```

Let me know how it goes, cheers!

**Comment by bberak** [comment] 2019-02-12 13:50
Or if the parent component must have the ```alignItem: 'center'``` style, use this workaround:

```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { GameEngine } from "react-native-game-engine";

const fireEvent = (entities, { touches }) => {
  console.log("Presses:", touches.filter(x => x.type == "press").length)
  return entities;
}

export default class App extends React.Component {
  render() {
    return (
      <View style={styles.container}>
        <GameEngine style={[StyleSheet.absoluteFill, { backgroundColor: "red" }]} systems={[fireEvent]} />
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  }
});
```

Cheers!

**Comment by ohmlnz** [comment] 2019-02-13 03:53
Hi @bberak,

How strange! However, my issue is actually triggered by something else. I've copied your example and realized that my GameEngine component wasn't at the root of my directory. I used to call it from within this Game component: 

```jsx
import React, { PureComponent } from 'react';
import { View } from 'react-native';
import EStyleSheet from 'react-native-extended-stylesheet';
import Game from './src/game';

export default class Engine extends PureComponent {
  render() {
    return (
      <View style={styles.container}>
        <Game />
      </View>
    );
  }
}

const styles = EStyleSheet.create({
  container: {
    flex: 1
  }
});
```

For some reason having it wrapped in a separate component messes things up. Any insights as to why? 

Thanks for your help anyway. I'm looking forward to exploring your engine. Great job by the way!

**Comment by bberak** [comment] 2019-02-13 03:59
To be honest @OthmanLan, I usually don't put the GameEngine component at the root either - but I haven't had any issues.

Would you be able to share an Expo Snack or repo with me to reproduce this?

**Comment by ohmlnz** [comment] 2019-02-13 04:23
@bberak, please disregard my previous comment. It looks like the issue comes from the `flex: 1` property. The engine needs to be wrapped in a View that contains it.

**Comment by bberak** [comment] 2019-02-14 06:51
That's interesting, I think there might've been a change in the React Native SDK recently to cause this. Or perhaps no one has experienced this because people usually set their parent container as flex: 1.

In any case, I can confirm that the GameEngine behaves exactly like a regular View would in this situation (it doesn't render).:

```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';

export default class App extends React.Component {
  render() {
    return (
      <View>
        <View style={{ flex: 1, backgroundColor: "red"}}><Text>This does not render</Text></View>
      </View>
    );
  }
}
```

I'm going to close this issue for now since the GameEngine behaves the same way a regular View does in this situation - which is the best we can hope for. 

All the best with your project @OthmanLan - let us know how it goes :)

Cheers!

**Closed as completed** 2019-02-14 06:55 UTC
